spring:
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/hackathon
    password: admin
    hikari:
      schema: cloudtechies
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

filepoller:
  regex: .*\.csv
  ingestionDir: /anand/temp/mnt/ingestion
  delay: 3s

kafka:
  clusterUrl: localhost:9092
  outputTopic: txn-data-input
  respTopic: client-resp-queue

simulator:
  enable: false
  interval: 5000
