spring:
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/hackathon
    password: admin
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

filepoller:
  regex: .*\.csv
  ingestionDir: /anand/temp/mnt/ingestion
  delay: 3s
