spring:
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/hackathon
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

filepoller:
  regex: .*\.csv
  ingestionDir: /hackathon/temp/mnt/ingestion
  delay: 3s
  skipMsgToKafka: false

kafka:
  clusterUrl: localhost:9092
  outputTopic: txn-data-input
  respTopic: client-resp-queue

simulator:
  enabled: false
  interval: 5000
